
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 103
#define YY_END_OF_BUFFER 104
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[369] =
    {   0,
        0,    0,    0,    0,  104,  102,    5,    5,   69,  102,
       60,   72,  102,   96,   97,   58,   56,   91,   57,   90,
       59,   52,   52,   94,   95,   65,   78,   66,   93,   51,
       51,  100,  101,   75,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       98,   74,   99,   73,    4,    3,    5,   64,    0,   55,
        0,   83,   70,   84,    0,    0,   81,   61,   79,   62,
       80,   89,    0,   53,    1,    2,   82,   53,   52,    0,
        0,   52,   52,    0,   52,   52,   52,   52,   52,   76,
       68,   63,   67,   77,   51,    0,    0,   85,   51,   51,

       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   13,   51,   51,   51,   51,   51,   51,
       21,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   86,   71,   55,    0,    0,    0,    0,
       54,    0,    0,   92,    0,   53,    0,   53,    0,   53,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   87,
       88,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   19,   51,   51,   23,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,

       51,   51,    0,    0,    0,    0,    0,   53,    0,   53,
       53,   52,   52,   52,   52,   52,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,    6,   51,    8,    9,
       51,   51,   51,   51,   15,   16,   51,   51,   20,   51,
       24,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   37,   51,   51,    0,    0,    0,    0,
       52,   52,   52,   52,   51,   51,   43,   51,   51,   51,
       51,   51,   51,   51,    7,   10,   51,   51,   51,   51,
       18,   51,   51,   51,   51,   28,   51,   51,   51,   51,
       51,   51,   35,   51,   51,   39,   52,   51,   51,   51,

       51,   51,   51,   51,   51,   51,   51,   51,   14,   17,
       22,   51,   51,   27,   29,   30,   31,   32,   33,   51,
       51,   51,   51,   51,   42,   51,   51,   51,   51,   51,
       51,   51,   51,   12,   51,   51,   34,   51,   51,   40,
       41,   44,   45,   51,   51,   51,   51,   50,   11,   25,
       26,   36,   38,   51,   47,   51,   51,   46,   51,   51,
       51,   51,   51,   51,   51,   49,   48,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   34,   34,   36,   34,   37,   34,   34,
       34,   34,   38,   39,   40,   34,   34,   41,   34,   34,
       42,   43,   44,   45,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   34,   56,   57,   58,   59,
       60,   61,   34,   62,   63,   64,   65,   66,   67,   68,
       69,   70,   71,   72,   73,   74,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    6,    6,
        1,    1,    1,    1,    1,    3,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    3,    1,    1,    7,    5,    5,    6,    6,
        6,    5,    7,    7,    7,    7,    7,    7,    8,    7,
        7,    8,    7,    8,    7,    8,    7,    8,    7,    7,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[378] =
    {   0,
        0,    0,  626,  625,  627,  630,   73,   75,  602,   74,
      601,   73,  581,  630,  630,  599,   69,  630,   70,   68,
       80,  103,   96,  630,  630,   66,  598,   74,  630,    0,
       95,  630,  630,  597,  113,  555,  557,   65,   41,   67,
       45,  558,   78,  557,  565,  102,  546,  157,  554,  559,
      630,   83,  630,  630,  630,  630,  106,  630,  124,  170,
      146,  630,  630,  630,  102,  160,  630,  630,  630,  630,
      630,  630,  597,  166,  630,  630,  630,  173,  214,  221,
      239,  134,   92,    0,  154,  249,  172,  122,  156,  587,
      630,  630,  630,  586,    0,  177,  566,  630,   74,  548,

      547,  555,  547,  544,  539,  548,  549,  536,  548,  535,
      550,  537,  543,  529,  530,  527,  527,  530,  527,  524,
        0,  123,  528,  210,  526,  173,  141,  530,  523,  239,
      126,  191,  528,  630,  630,  273,  577,  196,  244,    0,
      630,  273,    0,  630,  284,  630,  303,  630,  275,  307,
      242,  630,  545,  523,  272,  246,  630,  543,  521,  630,
      630,  522,  516,  515,  516,  514,  525,  509,  523,  507,
      503,  507,  519,  514,  502,  220,  516,  514,  510,  502,
      508,  511,    0,  497,  501,    0,  502,  499,  489,  487,
      489,  491,  498,  484,  482,  482,  494,  484,  488,  492,

      494,  483,  313,  360,  324,  405,  316,  364,  327,  409,
      630,  630,  321,  283,  309,  630,  486,  480,  480,  475,
      484,  481,  482,  468,  480,  471,    0,  473,    0,    0,
      464,  472,  461,  468,    0,    0,  462,  459,    0,  463,
        0,  458,  458,  457,  454,  466,  456,  460,  465,  464,
      455,  445,  446,    0,  434,  435,  217,    0,  199,    0,
      288,  630,  448,  419,  406,  409,    0,  406,  400,  405,
      395,  403,  404,  401,    0,    0,  390,  390,  395,  385,
        0,  392,  378,  385,  380,    0,  388,  379,  381,  356,
      365,  367,    0,  358,  360,    0,  630,  250,  365,  355,

      350,  345,  337,  352,  349,  352,  332,  331,    0,    0,
        0,  343,  344,    0,    0,    0,    0,    0,    0,  333,
      325,  318,  310,  320,    0,  303,  321,  322,  306,  317,
      316,  314,  307,    0,  293,  290,    0,  302,  300,    0,
        0,    0,    0,  288,  289,  258,  242,    0,    0,    0,
        0,    0,    0,  219,    0,  214,  210,    0,  192,  178,
      149,  148,   71,   49,   18,    0,    0,  630,  466,  474,
      482,  486,  492,  498,  502,  504,  506
    } ;

static const flex_int16_t yy_def[378] =
    {   0,
      368,    1,  369,  369,  368,  368,  368,  368,  368,  370,
      368,  368,  371,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  372,
      372,  368,  368,  368,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      368,  368,  368,  368,  368,  368,  368,  368,  370,  368,
      373,  368,  368,  368,  371,  374,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  375,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  372,  370,  371,  368,  372,  372,

      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  368,  368,  368,  368,  368,  370,  376,
      368,  371,  377,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  375,  368,  368,  368,  368,  368,
      368,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,

      372,  372,  370,  370,  371,  371,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  370,  204,  371,  206,
      368,  368,  368,  368,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  368,  372,  372,  372,

      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,    0,  368,  368,
      368,  368,  368,  368,  368,  368,  368
    } ;

static const flex_int16_t yy_nxt[705] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   23,   23,
       24,   25,   26,   27,   28,   29,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   31,
       30,   32,    6,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   30,   43,   30,   44,   30,   30,   30,
       30,   45,   46,   47,   48,   49,   50,   30,   30,   30,
       51,   52,   53,   54,   57,   57,   57,   57,   60,   63,
       68,  367,   73,   70,   74,   74,   74,   74,   90,   91,
       75,  113,   69,   71,   72,   76,   64,   93,   94,   96,

      114,  118,   97,   77,  119,  366,  134,   57,   57,  141,
       78,  110,   86,   86,   86,   86,   61,   78,  111,   79,
       79,   80,   80,  115,  112,  116,   81,  153,   60,  121,
      162,   87,  365,   81,  117,   88,  122,  163,   82,   99,
      100,  101,   83,   84,   66,  102,   81,  103,  154,  104,
      105,  106,   89,   81,  135,  125,  126,  158,  107,   85,
       88,   96,  139,  139,   97,  127,   61,   83,  128,  151,
       84,  136,  136,  152,   96,  130,  142,  142,  159,  185,
      198,   60,   74,   74,   74,   74,  186,  194,  199,   74,
       74,   74,   74,  152,  364,  157,  145,  146,  152,  363,

       96,  146,  195,  147,  148,  137,  141,  156,  148,  137,
      151,  157,  156,  140,  137,  131,  145,  146,  152,   61,
      157,   60,  146,  147,  148,  192,  362,  143,   78,  148,
       79,   79,   80,   80,  138,   78,  157,   80,   80,   80,
       80,   66,  193,   96,   81,  200,   97,  201,   60,   82,
      149,   81,  149,   83,  361,  150,  150,  150,  150,   61,
      203,  203,  188,   78,   81,   86,   86,   86,   86,  360,
       85,   81,  189,  190,  136,  136,  359,   96,   83,   81,
      141,  152,  231,  232,   87,  157,   61,  358,   88,  205,
      205,  150,  150,  150,  150,  207,  323,  207,  357,   81,

      208,  208,  208,  208,  356,   89,  152,  213,  137,  324,
      157,  214,  137,   88,  209,   66,  209,   60,  263,  210,
      210,  210,  210,  150,  150,  150,  150,  262,  215,  257,
      257,  141,  208,  208,  208,  208,  214,  138,  211,  264,
      259,  259,  211,  210,  210,  210,  210,  355,  262,  354,
      353,  352,  262,  351,  350,   61,  261,  349,  211,  348,
      262,  347,  346,  211,   60,  261,   66,  345,  344,  343,
      342,  341,  340,  262,  339,  338,  258,  258,  258,  258,
      208,  208,  208,  208,  337,  262,  258,  258,  258,  258,
      258,  258,  336,  335,  334,  146,  333,  332,  331,  146,

      330,  329,   61,  328,  327,  326,  258,  258,  258,  258,
      258,  258,  141,  325,  322,  146,  321,  320,  319,  318,
      146,  260,  260,  260,  260,  210,  210,  210,  210,  317,
      316,  260,  260,  260,  260,  260,  260,  315,  314,  313,
      148,  312,  311,  310,  148,  309,  308,   66,  307,  306,
      305,  260,  260,  260,  260,  260,  260,  304,  303,  302,
      148,  301,  300,  299,  298,  148,   55,   55,   55,   55,
       55,   55,   55,   55,   59,  297,   59,   59,   59,   59,
       59,   59,   65,  297,   65,  296,   65,   65,   65,   65,
       95,   95,   95,   95,   59,   59,   59,  295,  294,   59,

       65,   65,   65,  293,  292,   65,  155,  155,  204,  204,
      206,  206,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  216,  212,
      212,   96,  202,  197,  196,  191,  187,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,

      171,  170,  169,  168,  167,  166,  165,  164,   66,  161,
      160,  144,  133,  132,  129,  124,  123,  120,  109,  108,
       98,   92,   67,   66,   62,   58,  368,   56,   56,    5,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368
    } ;

static const flex_int16_t yy_chk[705] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    7,    8,    8,   10,   12,
       17,  365,   20,   19,   20,   20,   20,   20,   26,   26,
       21,   39,   17,   19,   19,   21,   12,   28,   28,   31,

       39,   41,   31,   21,   41,  364,   52,   57,   57,   65,
       23,   38,   23,   23,   23,   23,   10,   22,   38,   22,
       22,   22,   22,   40,   38,   40,   23,   83,   59,   43,
       99,   23,  363,   22,   40,   23,   43,   99,   22,   35,
       35,   35,   22,   22,   65,   35,   23,   35,   83,   35,
       35,   35,   23,   22,   52,   46,   46,   88,   35,   22,
       23,   48,   61,   61,   48,   46,   59,   22,   46,   82,
       22,   60,   60,   82,   60,   48,   66,   66,   88,  122,
      131,   96,   74,   74,   74,   74,  122,  127,  131,   78,
       78,   78,   78,   85,  362,   89,   74,   74,   82,  361,

      138,   74,  127,   78,   78,   60,  259,   87,   78,   60,
       85,   87,   89,   61,  138,   48,   74,   74,   85,   96,
       89,  257,   74,   78,   78,  126,  360,   66,   79,   78,
       79,   79,   79,   79,   60,   80,   87,   80,   80,   80,
       80,  259,  126,  130,   79,  132,  130,  132,  139,   79,
       81,   80,   81,   79,  359,   81,   81,   81,   81,  257,
      139,  139,  124,   86,   79,   86,   86,   86,   86,  357,
       79,   80,  124,  124,  136,  136,  356,  136,   79,   86,
      142,  151,  176,  176,   86,  156,  139,  354,   86,  142,
      142,  149,  149,  149,  149,  145,  298,  145,  347,   86,

      145,  145,  145,  145,  346,   86,  151,  155,  136,  298,
      156,  155,  136,   86,  147,  142,  147,  203,  214,  147,
      147,  147,  147,  150,  150,  150,  150,  261,  155,  203,
      203,  205,  207,  207,  207,  207,  155,  136,  150,  214,
      205,  205,  150,  209,  209,  209,  209,  345,  215,  344,
      339,  338,  261,  336,  335,  203,  213,  333,  150,  332,
      213,  331,  330,  150,  204,  215,  205,  329,  328,  327,
      326,  324,  323,  215,  322,  321,  204,  204,  204,  204,
      208,  208,  208,  208,  320,  213,  204,  204,  204,  204,
      204,  204,  313,  312,  308,  208,  307,  306,  305,  208,

      304,  303,  204,  302,  301,  300,  204,  204,  204,  204,
      204,  204,  206,  299,  295,  208,  294,  292,  291,  290,
      208,  206,  206,  206,  206,  210,  210,  210,  210,  289,
      288,  206,  206,  206,  206,  206,  206,  287,  285,  284,
      210,  283,  282,  280,  210,  279,  278,  206,  277,  274,
      273,  206,  206,  206,  206,  206,  206,  272,  271,  270,
      210,  269,  268,  266,  265,  210,  369,  369,  369,  369,
      369,  369,  369,  369,  370,  264,  370,  370,  370,  370,
      370,  370,  371,  263,  371,  256,  371,  371,  371,  371,
      372,  372,  372,  372,  373,  373,  373,  255,  253,  373,

      374,  374,  374,  252,  251,  374,  375,  375,  376,  376,
      377,  377,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  240,  238,  237,  234,  233,  232,  231,  228,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  185,  184,  182,  181,  180,
      179,  178,  177,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  159,  158,  154,
      153,  137,  133,  129,  128,  125,  123,  120,  119,  118,
      117,  116,  115,  114,  113,  112,  111,  110,  109,  108,

      107,  106,  105,  104,  103,  102,  101,  100,   97,   94,
       90,   73,   50,   49,   47,   45,   44,   42,   37,   36,
       34,   27,   16,   13,   11,    9,    5,    4,    3,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "clang.l"
#line 2 "clang.l"

#include <stdio.h>
#include <stdlib.h>
/* 标识符 */ 
#define ID              1
/* 关键字 */
#define AUTO            2
#define BREAK           3
#define CASE            4
#define CHAR            5
#define CONST           6
#define CONTINUE        7
#define DEFAULT         8
#define DO              9
#define DOUBLE         10
#define ELSE           11
#define ENUM           12
#define EXTERN         13
#define FLOAT          14
#define FOR            15
#define GOTO           16
#define IF             17
#define INLINE         18
#define INT            19
#define LONG           20
#define REGISTER       21
#define RESTRICT       22
#define RETURN         23
#define SHORT          24
#define SIGNED         25
#define SIZEOF         26
#define STATIC         27
#define STRUCT         28
#define SWITCH         29
#define TYPEDEF        30
#define UNION          31
#define UNSIGNED       32
#define VOID           33
#define VOLATILE       34
#define WHILE          35
#define _ALIGNAS       36
#define _ALIGNOF       37
#define _ATOMIC        38
#define _BOOL          39
#define _COMPLEX       40
#define _GENERIC       41
#define _IMAGINARY     42
#define _NORETURN      43
#define _STATIC_ASSERT 44
#define _THREAD_LOCAL  45
#define __FUNC__       46
/* 运算符 */
// 算术运算符
#define PLUS           47
#define MINUS          48
#define STAR           49
#define DIV            50
#define MOD            51
#define INC            52
#define DEC            53
// 关系运算符
#define LANGLE         54
#define RANGLE         55
#define EQ	           56		
#define	NE	           57
#define	GE	           58
#define LE             59
// 逻辑运算符
#define NOT            60
#define AND            61                    
#define OR             62
 // &,既可作位运算符也可作取地址符
#define ESPERLUETTE    63
// 位运算符
#define BNOT           64
#define BOR            65
#define XOR            66
#define LS             67 
#define RS             68
// 赋值运算符
#define DIRECTASSIGN   69 
#define ADDASSIGN      70
#define SUBASSIGN      71
#define MULASSIGN      72
#define DIVASSIGN      73
#define MODASSIGN      74             
#define BANDASSIGN     75
#define XORASSIGN      76
#define BORASSIGN      77
#define LSASSIGN       78
#define RSASSIGN       79
// 间接结构成员访问
#define ARROW          80
// 直接访问结构成员
#define PERIOD         81

/* 界符 */
#define COMMA          82
// 省略号
#define ELLIPSIS       83
// 问号
#define QUESTION       84
#define COLON          85
#define SEMICOLON      86
#define LPARENTHESE    87
#define RPARENTHESE    88 
#define LBRACE         89
#define RBRACE         90
#define LBRACKET       91
#define RBRACKET       92
/* 常量 */
// 数字常量
#define INT_CONSTANT   93
#define FLOAT_CONSTANT 94         
// 字符常量
#define CHARACTER      95
// 字符串常量
#define STRING         96
// 非法字符
#define ERRORCHAR      97

void terminationCheck(); 
void writeOut(int ch);
#line 845 "lex.yy.c"
/* 转义符 */
/* 十进制数位 */  
/* 不包括0的十进制数位 */ 
/* 十六进制数位 */ 
/* 八进制数位 */ 
/* 字符常量前缀 */ 
/* 十六进制前缀 */ 
/* 整数后缀 */ 
/* 浮点数后缀*/
/* 字符常量 */  
/* 十进制整数 */
/* 十六进制整数 */
/* 八进制整数 */
/* 整数 */
/* 浮点数 */
/* 标识符 */

#line 863 "lex.yy.c"

#define INITIAL 0
#define COMMENT2 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 166 "clang.l"

#line 168 "clang.l"
 /* 过滤注释 */
#line 1085 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 369 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 630 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 169 "clang.l"
{terminationCheck();}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 170 "clang.l"
{BEGIN COMMENT2;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 171 "clang.l"
{BEGIN INITIAL;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 172 "clang.l"
{;}
	YY_BREAK
/* 过滤空白符 */
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 176 "clang.l"
{;}
	YY_BREAK
/* 匹配关键字 */
case 6:
YY_RULE_SETUP
#line 179 "clang.l"
{return (AUTO);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 180 "clang.l"
{return (BREAK);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 181 "clang.l"
{return (CASE);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 182 "clang.l"
{return (CHAR);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 183 "clang.l"
{return (CONST);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 184 "clang.l"
{return (CONTINUE);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 185 "clang.l"
{return (DEFAULT);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 186 "clang.l"
{return (DO);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 187 "clang.l"
{return (DOUBLE);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 188 "clang.l"
{return (ELSE);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 189 "clang.l"
{return (ENUM);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 190 "clang.l"
{return (EXTERN);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 191 "clang.l"
{return (FLOAT);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 192 "clang.l"
{return (FOR);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 193 "clang.l"
{return (GOTO);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 194 "clang.l"
{return (IF);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 195 "clang.l"
{return (INLINE);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 196 "clang.l"
{return (INT);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 197 "clang.l"
{return (LONG);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 198 "clang.l"
{return (REGISTER);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 199 "clang.l"
{return (RESTRICT);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 200 "clang.l"
{return (RETURN);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 201 "clang.l"
{return (SHORT);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 202 "clang.l"
{return (SIGNED);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 203 "clang.l"
{return (SIZEOF);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 204 "clang.l"
{return (STATIC);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 205 "clang.l"
{return (STRUCT);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 206 "clang.l"
{return (SWITCH);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 207 "clang.l"
{return (TYPEDEF);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 208 "clang.l"
{return (UNION);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 209 "clang.l"
{return (UNSIGNED);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 210 "clang.l"
{return (VOID);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 211 "clang.l"
{return (VOLATILE);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 212 "clang.l"
{return (WHILE);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 213 "clang.l"
{return (_ALIGNAS);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 214 "clang.l"
{return (_ALIGNOF);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 215 "clang.l"
{return (_ATOMIC);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 216 "clang.l"
{return (_BOOL);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 217 "clang.l"
{return (_COMPLEX);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 218 "clang.l"
{return (_GENERIC);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 219 "clang.l"
{return (_IMAGINARY);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 220 "clang.l"
{return (_NORETURN);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 221 "clang.l"
{return (_STATIC_ASSERT);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 222 "clang.l"
{return (_THREAD_LOCAL);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 223 "clang.l"
{return (__FUNC__);}
	YY_BREAK
/* 匹配标识符 */
case 51:
YY_RULE_SETUP
#line 225 "clang.l"
{return (ID);}
	YY_BREAK
/* 匹配数字常量 */
/* 匹配整数  */
case 52:
YY_RULE_SETUP
#line 229 "clang.l"
{return (INT_CONSTANT);}
	YY_BREAK
/* 匹配浮点数常量 */
case 53:
YY_RULE_SETUP
#line 231 "clang.l"
{return (FLOAT_CONSTANT);}
	YY_BREAK
/* 匹配字符常量 */
case 54:
YY_RULE_SETUP
#line 233 "clang.l"
{return (CHARACTER);}
	YY_BREAK
/* 匹配字符串常量 */
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 235 "clang.l"
{return (STRING);}
	YY_BREAK
/* 匹配运算符 */
/* 匹配算术运算符 */
case 56:
YY_RULE_SETUP
#line 239 "clang.l"
{return (PLUS);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 240 "clang.l"
{return (MINUS);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 241 "clang.l"
{return (STAR);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 242 "clang.l"
{return (DIV);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 243 "clang.l"
{return (MOD);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 244 "clang.l"
{return (INC);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 245 "clang.l"
{return (DEC);}
	YY_BREAK
/* 匹配关系运算符 */
case 63:
YY_RULE_SETUP
#line 247 "clang.l"
{return (EQ);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 248 "clang.l"
{return (NE);}
	YY_BREAK
/* >,<既是关系运算符也是界符 */
case 65:
YY_RULE_SETUP
#line 250 "clang.l"
{return (LANGLE);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 251 "clang.l"
{return (RANGLE);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 252 "clang.l"
{return (GE);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 253 "clang.l"
{return (LE);}
	YY_BREAK
/* 匹配逻辑运算符 */
case 69:
YY_RULE_SETUP
#line 255 "clang.l"
{return (NOT);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 256 "clang.l"
{return (AND);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 257 "clang.l"
{return (OR);}
	YY_BREAK
/* 匹配&运算符 */
case 72:
YY_RULE_SETUP
#line 259 "clang.l"
{return (ESPERLUETTE);}
	YY_BREAK
/* 匹配位运算符 */
case 73:
YY_RULE_SETUP
#line 261 "clang.l"
{return (BNOT);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 262 "clang.l"
{return (BOR);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 263 "clang.l"
{return (XOR);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 264 "clang.l"
{return (LS);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 265 "clang.l"
{return (RS);}
	YY_BREAK
/* 匹配赋值运算符 */
case 78:
YY_RULE_SETUP
#line 267 "clang.l"
{return (DIRECTASSIGN);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 268 "clang.l"
{return (ADDASSIGN);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 269 "clang.l"
{return (SUBASSIGN);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 270 "clang.l"
{return (MULASSIGN);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 271 "clang.l"
{return (DIVASSIGN);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 272 "clang.l"
{return (MODASSIGN);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 273 "clang.l"
{return (BANDASSIGN);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 274 "clang.l"
{return (XORASSIGN);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 275 "clang.l"
{return (BORASSIGN);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 276 "clang.l"
{return (LSASSIGN);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 277 "clang.l"
{return (RSASSIGN);}
	YY_BREAK
/* 匹配成员访问运算符 */
case 89:
YY_RULE_SETUP
#line 279 "clang.l"
{return (ARROW);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 280 "clang.l"
{return (PERIOD);}
	YY_BREAK
/* 匹配界符(某些界符也同时作为运算符，如?和：搭配是条件运算符) */
case 91:
YY_RULE_SETUP
#line 282 "clang.l"
{return (COMMA);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 283 "clang.l"
{return (ELLIPSIS);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 284 "clang.l"
{return (QUESTION);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 285 "clang.l"
{return (COLON);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 286 "clang.l"
{return (SEMICOLON);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 287 "clang.l"
{return (LPARENTHESE);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 288 "clang.l"
{return (RPARENTHESE);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 289 "clang.l"
{return (LBRACE);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 290 "clang.l"
{return (RBRACE);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 291 "clang.l"
{return (LBRACKET);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 292 "clang.l"
{return (RBRACKET);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 294 "clang.l"
{return (ERRORCHAR);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 297 "clang.l"
ECHO;
	YY_BREAK
#line 1678 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 369 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 369 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 368);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 297 "clang.l"


int yywrap() {
  return 1;
}

int fileNum;

void terminationCheck() {
	char current, prev;
	prev = 0;
  
	while ((current = input()))      
	{
		if (prev == '*' && current == '/') return;
		prev = current;
	}
	fprintf(stderr, "unterminated comment\n");
	fclose(yyin);
	if (fileNum > 1) fclose(yyout);
	exit(-1);
}

void writeOut(int ch) {
  switch(ch) {
	case AUTO:           fprintf(yyout, "(AUTO, %s)\n", yytext);          break;
	case BREAK:          fprintf(yyout, "(BREAK, %s)\n", yytext);         break;
	case CASE:           fprintf(yyout, "(CASE, %s)\n", yytext);          break;
	case CHAR:           fprintf(yyout, "(CHAR, %s)\n", yytext);          break;
	case CONST:          fprintf(yyout, "(CONST, %s)\n", yytext);         break;
	case CONTINUE:       fprintf(yyout, "(BREAK, %s)\n", yytext);         break;
	case DEFAULT:        fprintf(yyout, "(DEFAULT, %s)\n", yytext);       break;
	case DO:             fprintf(yyout, "(DO, %s)\n", yytext);            break;
	case DOUBLE:         fprintf(yyout, "(DOUBLE, %s)\n", yytext);        break;
	case ELSE:           fprintf(yyout, "(ELSE, %s)\n", yytext);          break;
	case ENUM:           fprintf(yyout, "(ENUM, %s)\n", yytext);          break;
	case EXTERN:         fprintf(yyout, "(EXTERN, %s)\n", yytext);        break;
	case FLOAT:          fprintf(yyout, "(FLOAT, %s)\n", yytext);         break;
	case FOR:            fprintf(yyout, "(FOR, %s)\n", yytext);           break;
	case GOTO:           fprintf(yyout, "(GOTO, %s)\n", yytext);          break;
	case IF:             fprintf(yyout, "(IF, %s)\n", yytext);            break;
	case INLINE:         fprintf(yyout, "(INLINE, %s)\n", yytext);        break;
	case INT:            fprintf(yyout, "(INT, %s)\n", yytext);           break;
	case LONG:           fprintf(yyout, "(LONG, %s)\n", yytext);          break;
	case REGISTER:       fprintf(yyout, "(REGISTER, %s)\n", yytext);      break;
	case RESTRICT:       fprintf(yyout, "(RESTRICT, %s)\n", yytext);      break;
	case RETURN:         fprintf(yyout, "(RETURN, %s)\n", yytext);        break;
	case SHORT:          fprintf(yyout, "(SHORT, %s)\n", yytext);         break;
	case SIGNED:         fprintf(yyout, "(SIGNED, %s)\n", yytext);        break;
	case SIZEOF:         fprintf(yyout, "(SIZEOF, %s)\n", yytext);        break;
	case STATIC:         fprintf(yyout, "(STATIC, %s)\n", yytext);        break;
	case STRUCT:         fprintf(yyout, "(STRUCT, %s)\n", yytext);        break;
	case SWITCH:         fprintf(yyout, "(SWITCH, %s)\n", yytext);        break;
	case TYPEDEF:        fprintf(yyout, "(TYPEDEF, %s)\n", yytext);       break;
	case UNION:          fprintf(yyout, "(UNION, %s)\n", yytext);         break; 
	case UNSIGNED:       fprintf(yyout, "(UNSIGNED, %s)\n", yytext);      break;
	case VOID:           fprintf(yyout, "(VOID, %s)\n", yytext);          break;
	case VOLATILE:       fprintf(yyout, "(VOLATILE, %s)\n", yytext);      break;
	case WHILE:          fprintf(yyout, "(WHILE, %s)\n", yytext);         break;
	case _ALIGNAS:       fprintf(yyout, "(ALIGNAS, %s)\n", yytext);       break;
	case _ALIGNOF:       fprintf(yyout, "(ALIGNOF, %s)\n", yytext);       break;
	case _ATOMIC:        fprintf(yyout, "(ATOMIC, %s)\n", yytext);        break;
	case _BOOL:          fprintf(yyout, "(BOOL, %s)\n", yytext);          break;
	case _COMPLEX:       fprintf(yyout, "(COMPLEX, %s)\n", yytext);       break;
	case _GENERIC:       fprintf(yyout, "(GENERIC, %s)\n", yytext);       break;
	case _IMAGINARY:     fprintf(yyout, "(IMAGINARY, %s)\n", yytext);     break;
	case _NORETURN:      fprintf(yyout, "(NORETURN, %s)\n", yytext);      break;
	case _STATIC_ASSERT: fprintf(yyout, "(STATIC_ASSERT, %s)\n", yytext); break;
	case _THREAD_LOCAL:  fprintf(yyout, "(THREAD_LOCAL, %s)\n", yytext);  break;
	case __FUNC__:       fprintf(yyout, "(FUNC, %s)\n", yytext);          break;
	
	case ID:             fprintf(yyout, "(ID, %s)\n", yytext);            break;

	case INT_CONSTANT:   fprintf(yyout, "(INT_CONSTANT, %s)\n", yytext);  break;
	case FLOAT_CONSTANT: fprintf(yyout, "(FLOAT_CONSTANT, %s)\n", yytext);break;
	case CHARACTER:      fprintf(yyout, "(CHARACTER, %s)\n", yytext);     break;
	case STRING:         fprintf(yyout, "(STRING, %s)\n", yytext);        break;

	case PLUS:           fprintf(yyout, "(PLUS, %s)\n", yytext);          break;
	case MINUS:          fprintf(yyout, "(MINUS, %s)\n", yytext);         break;
	case STAR:           fprintf(yyout, "(STAR, %s)\n", yytext);          break;
	case DIV:            fprintf(yyout, "(DIV, %s)\n", yytext);           break;
	case MOD:            fprintf(yyout, "(MOD, %s)\n", yytext);           break;
	case INC:            fprintf(yyout, "(INC, %s)\n", yytext);           break;
	case DEC:            fprintf(yyout, "(DEC, %s)\n", yytext);           break;
	case EQ:             fprintf(yyout, "(EQ, %s)\n", yytext);            break;
	case NE:             fprintf(yyout, "(NE, %s)\n", yytext);            break;
	case LANGLE:         fprintf(yyout, "(LANGLE, %s)\n", yytext);        break;
	case RANGLE:         fprintf(yyout, "(RANGLE, %s)\n", yytext);        break;
	case GE:             fprintf(yyout, "(GE, %s)\n", yytext);            break;
	case LE:             fprintf(yyout, "(LE, %s)\n", yytext);            break;
	case NOT:            fprintf(yyout, "(NOT, %s)\n", yytext);           break;
	case AND:            fprintf(yyout, "(AND, %s)\n", yytext);           break;
	case OR:             fprintf(yyout, "(OR, %s)\n", yytext);            break;
	case ESPERLUETTE:    fprintf(yyout, "(ESPERLUETTE, %s)\n", yytext);   break;
	case BNOT:           fprintf(yyout, "(BNOT, %s)\n", yytext);          break;
	case BOR:            fprintf(yyout, "(BOR, %s)\n", yytext);           break;
	case XOR:            fprintf(yyout, "(XOR, %s)\n", yytext);           break;
	case LS:             fprintf(yyout, "(LS, %s)\n", yytext);            break;
	case RS:             fprintf(yyout, "(RS, %s)\n", yytext);            break;
	case DIRECTASSIGN:   fprintf(yyout, "(DIRECTASSIGN, %s)\n", yytext);  break;
	case ADDASSIGN:      fprintf(yyout, "(ADDASSIGN, %s)\n", yytext);     break;
	case SUBASSIGN:      fprintf(yyout, "(SUBASSIGN, %s)\n", yytext);     break;
	case MULASSIGN:      fprintf(yyout, "(MULASSIGN, %s)\n", yytext);     break;
	case DIVASSIGN:      fprintf(yyout, "(DIVASSIGN, %s)\n", yytext);     break;
	case MODASSIGN:      fprintf(yyout, "(MODASSIGN, %s)\n", yytext);     break;
	case BANDASSIGN:     fprintf(yyout, "(BANDASSIGN, %s)\n", yytext);    break;
	case XORASSIGN:      fprintf(yyout, "(XORASSIGN, %s)\n", yytext);     break;
	case BORASSIGN:      fprintf(yyout, "(BORASSIGN, %s)\n", yytext);     break;
	case LSASSIGN:       fprintf(yyout, "(LSASSIGN, %s)\n", yytext);      break;
	case RSASSIGN:       fprintf(yyout, "(RSASSIGN, %s)\n", yytext);      break;
	case ARROW:          fprintf(yyout, "(ARROW, %s)\n", yytext);         break;
	case PERIOD:         fprintf(yyout, "(PERIOD, %s)\n", yytext);        break;

	case COMMA:          fprintf(yyout, "(COMMA, %s)\n", yytext);         break;
	case ELLIPSIS:       fprintf(yyout, "(ELLIPSIS, %s)\n", yytext);      break;
	case QUESTION:       fprintf(yyout, "(QUESTION, %s)\n", yytext);      break;
	case COLON:          fprintf(yyout, "(COLON, %s)\n", yytext);         break;
	case SEMICOLON:      fprintf(yyout, "(SEMICOLON, %s)\n", yytext);     break;
	case LPARENTHESE:    fprintf(yyout, "(LPARENTHESE, %s)\n", yytext);   break;
	case RPARENTHESE:    fprintf(yyout, "(RPARENTHESE, %s)\n", yytext);   break;
	case LBRACE:         fprintf(yyout, "(LBRACE, %s)\n", yytext);        break;
	case RBRACE:         fprintf(yyout, "(RBRACE, %s)\n", yytext);        break;
	case LBRACKET:       fprintf(yyout, "(LBRACKET, %s)\n", yytext);      break;
	case RBRACKET:       fprintf(yyout, "(RBRACKET, %s)\n", yytext);      break;
	
	case ERRORCHAR:      fprintf(yyout, "(ERRORCHAR, %s)\n", yytext);     break;

    default:break;
  }
  return;
}


int main (int argc, char ** argv){
	int typeCode;
	fileNum = argc - 1;
	if (argc < 2) {
		fprintf(stderr, "Usage: <program_name> <input_file> <output_file>(optional)\n");
		exit(-1);	
	}
	
	if ((yyin = fopen(argv[1], "r")) == NULL) {
	    fprintf(stderr, "Can't open file %s\n", argv[1]);
		exit(-1);
	}
	if (argc >= 3) {
		if ((yyout = fopen(argv[2], "w")) == NULL) {
	    	fprintf(stderr, "Can't open file %s\n", argv[2]);
			fclose(yyin);
			exit(-1);
		}	  
	}

	while (typeCode = yylex()) {
		writeOut(typeCode);
	}

	fclose(yyin);
	if (argc >= 3) fclose(yyout);
	return 0;
}

